hello-world:
  tags:
    - siphon
    - popos
  script:
    - echo "Hello, world! Running on $(hostname) at $(date)"
    - echo "Current directory: $(pwd)"
    - echo "Files in directory:"
    - ls -la
