hello-world:
  script: echo "Hello, world!"

secure-job:
  tags:
    - main-only
    - secure
  script: echo "This job should run on your protected runner"

untagged-job:
  script: 
    - echo "This job has no tags"
    - echo "It should run on any runner with run_untagged=true"

should-not-run:
  tags:
    - different-tag
  only:
    - tags
  script: echo "This job should remain pending because no runner has this tag"