name: Publish APT Package
on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'
    branches:
      main

env:
  VERSION: 1.5.0

jobs:
  apt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Debian Packaging Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y devscripts build-essential dh-make debhelper python3-all dput dh-python python3-all-dev

      - name: Create Tarball
        run: |
          PACKAGE_NAME="siphon" # Ensure this is your correct package name
          # PACKAGE_VERSION="${{ env.VERSION }}" # Version not used in directory name
          PACKAGE_DIR="${PACKAGE_NAME}" # Top-level dir: "siphon" (package name only)
      
          mkdir $PACKAGE_DIR
          mkdir $PACKAGE_DIR/debian # Create 'debian' subdirectory inside the source dir
      
          # Copy files (excluding 'artifacts' and '.git*') into the source dir
          find . -maxdepth 1 -not -name artifacts -not -name debian -not -path "./.git*" -print0 | cpio -pdm0 $PACKAGE_DIR
          # Copy debian directory into the source dir
          cp -r debian/* $PACKAGE_DIR/debian/
      
          mkdir artifacts
      
          # Create tarball with top-level dir "siphon" (package name only)
          tar -czvf artifacts/siphon_${{ env.VERSION }}.tar.gz -C $PACKAGE_DIR .
      
          rm -rf $PACKAGE_DIR
      
      - name: Upload Tarball Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tarball-artifact
          path: artifacts/siphon_${{ env.VERSION }}.tar.gz

      - name: Publish to PPA
        uses: atxtechbro/publish-ppa-package@main
        with:
          repository: "atxtechbro/siphon-cli"
          gpg_private_key: ${{ secrets.APT_GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.APT_GPG_PASSPHRASE }}
          tarball: artifacts/siphon_${{ env.VERSION }}.tar.gz
          deb_email: "morganj2k@gmail.com"
          deb_fullname: "Morgan Joyce"
          debian_dir: debian
          series: focal
          debmake_arguments: "-p siphon -u 1.5.0"
