name: Publish APT Package
on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  apt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Version from Tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Create Original Tarball
        run: |
          ORIG_TARBALL_NAME="siphon_${{ steps.get_version.outputs.version }}.orig.tar.gz"
          git archive --format=tar.gz --prefix=siphon-${{ steps.get_version.outputs.version }}/ -o "$ORIG_TARBALL_NAME" HEAD
          ls -l

      - name: Create Debian Source Tarball
        run: |
          TEMP_DIR="temp_build"
          mkdir "$TEMP_DIR"
          cp -r ./* "$TEMP_DIR/siphon_${{ steps.get_version.outputs.version }}/"  # Corrected line!
          DEB_TARBALL_NAME="siphon_${{ steps.get_version.outputs.version }}.tar.gz"
          tar -czvvvf "$DEB_TARBALL_NAME" -C "$TEMP_DIR" "siphon-${{ steps.get_version.outputs.version }}"
          ls -l
          rm -rf "$TEMP_DIR"

      - name: Upload Tarball Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tarball-artifact
          path: |
            siphon_${{ steps.get_version.outputs.version }}.orig.tar.gz
            siphon_${{ steps.get_version.outputs.version }}.tar.gz
          if-no-files-found: error

      - name: Build Debian Package with debmake
        run: |
          sudo apt-get update -y
          sudo apt-get install -y debmake lintian
          debmake -f "siphon_${{ steps.get_version.outputs.version }}.tar.gz" -p "siphon_" -u "${{ steps.get_version.outputs.version }}-1"

      - name: Run Lintian
        run: |
          lintian "siphon_${{ steps.get_version.outputs.version }}-1_all.changes"

      # Add steps here to upload the .deb and .changes files.