name: Publish APT Package
on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'
    branches:
      main

env:
  VERSION: 1.5.0

jobs:
  apt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Debian Packaging Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y devscripts build-essential dh-make debhelper python3-all dput dh-python python3-all-dev

      - name: Create Tarball
        run: |
          set -e  # Exit immediately if any command fails

          PACKAGE_NAME="siphon"
          PACKAGE_VERSION="${{ env.VERSION }}"
          PACKAGE_BASE_DIR="${PACKAGE_NAME}" # Top-level dir for both tarballs will be just "siphon"

          # 1. Create Original Source Tarball (siphon-1.5.0.orig.tar.gz)
          mkdir original-source
          # Copy ONLY source code files (exclude debian dir and artifacts)
          find . -maxdepth 1 -not -name artifacts -not -name debian -not -path "./.git*" -print0 | cpio -pdm0 original-source
          cd original-source # Change to original-source dir for tar command

          echo "DEBUG: Current working directory (before orig.tar.gz):"
          pwd # *** DEBUG - PRINT WORKING DIRECTORY ***
          echo "DEBUG: Listing files in current directory (before orig.tar.gz):"
          ls -l # *** DEBUG - LIST DIRECTORY CONTENTS ***

          echo "DEBUG: Creating original source tarball..."
          tar -czvvvf "siphon_${{ env.VERSION }}.orig.tar.gz" .
          if [ $? -ne 0 ]; then # Check exit code of tar
            echo "ERROR: Failed to create original source tarball!"
            exit 1
          fi
          cd .. # Go back to workflow root

          # 2. Create Debian Source Tarball (siphon_1.5.0.tar.gz) - (May not be needed, but create for now)
          PACKAGE_DIR="${PACKAGE_NAME}" # Top-level dir: "siphon" (package name only)
          mkdir $PACKAGE_DIR
          mkdir $PACKAGE_DIR/debian
          # Copy source files (excluding artifacts, debian, .git*)
          find . -maxdepth 1 -not -name artifacts -not -name debian -not -path "./.git*" -print0 | cpio -pdm0 $PACKAGE_DIR
          # Copy debian dir
          cp -r debian/* "$PACKAGE_DIR/debian/"
          echo "DEBUG: Creating Debian source tarball..."
          tar -czvvvf "siphon_${{ env.VERSION }}.tar.gz" -C "$PACKAGE_DIR" .
          if [ $? -ne 0 ]; then # Check exit code of tar
            echo "ERROR: Failed to create Debian source tarball!"
            exit 1
          fi
          rm -rf $PACKAGE_DIR

          rm -rf original-source # Cleanup temporary original-source dir

      - name: Upload Tarball Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tarball-artifact
          path: "siphon_${{ env.VERSION }}.tar.gz"

      - name: Publish to PPA
        uses: atxtechbro/publish-ppa-package@main
        with:
          repository: "atxtechbro/siphon-cli"
          gpg_private_key: ${{ secrets.APT_GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.APT_GPG_PASSPHRASE }}
          tarball: "siphon_${{ env.VERSION }}.tar.gz"
          deb_email: "morganj2k@gmail.com"
          deb_fullname: "Morgan Joyce"
          debian_dir: debian
          series: focal
          debmake_arguments: "-p siphon -u 1.5.0"
