name: Publish APT Package
on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'
    branches:
      main

env:
  VERSION: 1.5.0

jobs:
  apt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Tarball
        run: |
          # 1. Create Original Source Tarball (siphon-1.5.0.orig.tar.gz)
          # ... existing code ...
      
          # 2. Create Debian Source Tarball (siphon_1.5.0.tar.gz)
          PACKAGE_NAME="siphon"
          mkdir $PACKAGE_NAME
          mkdir $PACKAGE_NAME/debian
          # Copy source files (excluding artifacts, debian, .git*)
          find . -maxdepth 1 -not -name artifacts -not -name debian -not -path "./.git*" -print0 | cpio -pdm0 $PACKAGE_NAME
          # Copy debian dir
          cp -r debian/* "$PACKAGE_NAME/debian/"
          echo "DEBUG: Creating Debian source tarball..."
          tar -czvvvf "siphon_${{ env.VERSION }}.tar.gz" -C "$PACKAGE_NAME" .
          if [ $? -ne 0 ]; then # Check exit code of tar
            echo "ERROR: Failed to create Debian source tarball!"
            exit 1
          fi
          rm -rf $PACKAGE_NAME

      - name: Upload Tarball Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tarball-artifact
          path: "siphon_${{ env.VERSION }}.orig.tar.gz"

      - name: Publish to PPA
        uses: yuezk/publish-ppa-package@v2
        with:
          repository: "atxtechbro/siphon-cli"
          gpg_private_key: ${{ secrets.APT_GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.APT_GPG_PASSPHRASE }}
          tarball: "siphon_${{ env.VERSION }}.orig.tar.gz"
          deb_email: "morganj2k@gmail.com"
          deb_fullname: "Morgan Joyce"
          debian_dir: debian
          series: focal
          debmake_arguments: "-f /tmp/workspace/source/siphon_1.5.0.tar.gz -p siphon -u 1.5.0"
