name: Publish APT Package
on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'
    branches:
      main

env:
  VERSION: 1.5.0

jobs:
  apt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Debian Packaging Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y devscripts build-essential dh-make debhelper python3-all dput dh-python python3-all-dev

      - name: Create Tarball
        run: |
          mkdir artifacts
          tar -czvf artifacts/siphon_${{ env.VERSION }}.tar.gz --exclude=.git .
    
      - name: Upload Tarball Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tarball-artifact
          path: artifacts/siphon_${{ env.VERSION }}.tar.gz

      - name: Publish to PPA
        uses: yuezk/publish-ppa-package@v2
        with:
          repository: "atxtechbro/siphon-cli"
          gpg_private_key: ${{ secrets.APT_GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.APT_GPG_PASSPHRASE }}
          tarball: artifacts/siphon_${{ env.VERSION }}.tar.gz
          deb_email: "morganj2k@gmail.com"
          deb_fullname: "Morgan Joyce"
          debian_dir: debian
          series: focal
