name: Publish APT Package
on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'
    branches:
      main

jobs:
  apt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures all tags are available

      - name: Install Debian Packaging Tools
        run: sudo apt update && sudo apt install -y debhelper devscripts dpkg-dev

      - name: Import GPG Key for Signing
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.APT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.APT_GPG_PASSPHRASE }}

      - name: Generate Debian Changelog
        run: |
          mkdir -p debian
          echo "siphon (1.5.0) unstable; urgency=medium" > debian/changelog
          echo "" >> debian/changelog
          echo "  * Automated release 1.5.0" >> debian/changelog
          echo "" >> debian/changelog
          echo " -- Morgan Joyce <morganj2k@gmail.com>  $(date -R)" >> debian/changelog

      - name: Verify GPG Key Import
        run: gpg --list-secret-keys --keyid-format LONG
      
      - name: Install Debian Packaging Tools and Python3 Build Deps
        run: sudo apt update && sudo apt install -y build-essential debhelper devscripts dpkg-dev python3-all dh-python

      - name: Build Debian Package
        run: |
          mkdir -p debian
          echo "Building package for version 1.5.0"
          dpkg-buildpackage -us -uc

      - name: Upload Package to PPA
        env:
          SSH_PRIVATE_KEY: ${{ secrets.APT_SSH_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp ../siphon.1.5.0_amd64.deb username@ppa.launchpad.net:/incoming
