name: Build Debian Package

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  # release:  # Use release trigger for production, push for dev.
  #   types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Version from Tag or Fallback
        id: get_version
        run: |
          if [[ "${{ github.ref_name }}" == v* ]]; then
            VERSION=${GITHUB_REF_NAME#v}
          else
            VERSION="main"  # Fallback version for pushes to main
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y debmake lintian build-essential devscripts debhelper-compat dh-python python3-all

      - name: Build Debian Package
        id: build_package
        run: |
          # Use debuild, a cleaner way to build Debian packages
          # '-b' builds a binary-only package (since it's pure Python, we don't need source)
          # '-uc' and '-us' skip signing (for this example; you'd add signing steps later)
          debuild -b -uc -us
        working-directory: .  # Ensure we are in the root

      - name: Move artifacts to current directory
        run: |
          cp ../siphon_*.deb ./
          cp ../siphon_*.changes ./
    
      - name: Upload Artifacts (Deb and Changes)
        uses: actions/upload-artifact@v4
        with:
          name: debian-package
          path: |
            ./siphon_*.deb
            ./siphon_*.changes

