name: Publish Chocolatey Package
on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'
    branches:
      main

jobs:
  chocolatey:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

      - name: Build Executable (PyInstaller)
        run: |
          pip install pyinstaller
          pyinstaller --onefile siphon.py --name siphon.exe
          mv dist/siphon.exe.

      # Add these steps to include LICENSE.txt and VERIFICATION.txt
      - name: Copy LICENSE.txt
        run: Copy-Item LICENSE.txt.

      - name: Generate VERIFICATION.txt
        run: Get-FileHash -Algorithm SHA256.\siphon.exe | Format-List | Out-File -Encoding UTF8 VERIFICATION.txt

      - name: Package Chocolatey Release
        run: choco pack siphon.nuspec

      # Use a wildcard to push the latest.nupkg
      - name: Publish to Chocolatey
        run: choco push *.nupkg --source https://push.chocolatey.org/ --api-key ${{ secrets.CHOCOLATEY_API_KEY }}
