name: Publish Chocolatey Package
on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

jobs:
  chocolatey:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify Chocolatey (Optional)
        run: choco --version

      - name: Build Executable (PyInstaller)
        run: |
          pip install pyinstaller
          pyinstaller --onefile siphon.py --name siphon.exe
          mv dist/siphon.exe

      - name: Create choco directory
        run: New-Item -ItemType Directory -Path "choco"
  
      - name: Copy files to choco directory
        run: |
          Copy-Item LICENSE.txt choco\
          Copy-Item siphon.exe choco\

      - name: Generate VERIFICATION.txt in choco directory
        run: Get-FileHash -Algorithm SHA256 choco\siphon.exe | Format-List | Out-File -Encoding UTF8 choco\VERIFICATION.txt

      - name: Package Chocolatey Release
        run: |
          cd choco
          choco pack ../siphon.nuspec

      - name: Publish to Chocolatey
        run: |
          cd choco
          choco push siphon.1.5.0.nupkg --source https://push.chocolatey.org/ --api-key ${{ secrets.CHOCOLATEY_API_KEY }}
