name: Publish Chocolatey Package
on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'
    branches:
      main

jobs:
  chocolatey:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures all tags are available

      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

      - name: Build Executable (PyInstaller)
        run: |
          pip install pyinstaller
          pyinstaller --onefile siphon.py --name siphon.exe
          mv dist/siphon.exe .

      - name: Check if .nupkg file is created
        run: |
          Get-ChildItem -Recurse -Filter *.nupkg

      - name: Package Chocolatey Release
        run: choco pack siphon.nuspec  # Explicitly specify the .nuspec file

      - name: Publish to Chocolatey
        run: choco push siphon.${{ env.VERSION }}.nupkg --source https://push.chocolatey.org/ --api-key ${{ secrets.CHOCOLATEY_API_KEY }}
