name: Release and Publish

permissions:
  contents: write
  issues: write

on:
  push:
    tags:
      - "v*"

jobs:
  release-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install Node.js dependencies
        run: npm install # This will install semantic-release and its plugins

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine build pycryptodome pyinstaller

      # Build Python package
      - name: Build package
        run: python -m build

      # Create standalone Linux executable
      - name: Build Linux executable
        run: pyinstaller --onefile siphon.py --name siphon-linux

      # Run semantic-release for versioning, GitHub releases, and PyPI publishing
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: npx semantic-release

      # Attach additional assets to the GitHub release
      - name: Attach assets to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/siphon-linux
          generate_release_notes: false # semantic-release already generates notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
